### ISSUE TITLE
Discuss file versioning best practices

### ISSUE THREAD

**Issue by jcconway** [gentzkow/template#32]
The goal of this issue is to decide on suggested best practices for implementing file versioning when using this template.

**Comment by jcconway** [comment]
@gentzkow:
Following up on our earlier VirusPolicy discussion of proper file versioning, I've opened up this issue to discuss best practices going forward. Thanks in advance for your advice, and I'll be happy to implement whatever we decide in our current projects.

---
**Current Implementation and Problem:**

In VirusPolicy we are facing the following issue. We have several data files which are updated regularly (eg weekly), and at present file versions are updated by modifying `config_user.yaml`. For example, `config_user.yaml` might be modified as:
`county_day_data: "/Users/jacob/Dropbox (Personal)/VirusPolicy/county_day_data_20200618.csv"` (From)
`county_day_data: "/Users/jacob/Dropbox (Personal)/VirusPolicy/county_day_data_20200625.csv"` (To)

The file `external.txt` then includes `county_day_data.csv | {county_day_data}` and Stata/R/Python programs then load `external/county_day_data.csv`.

Organizing file versioning in this way seems like bad practice to me in that file versioning is handled in `config_user.yaml` files which aren't committed. This provides less documentation of files used and might lead to discrepancies across users in the version of files used (eg someone forgets to update their `config_user.yaml`).

---
**Suggested Implementation:**
My suggestion going forward is that we generally handle file versioning within `external.txt` and `internal.txt` rather than within `config_user.yaml` or within Stata/R/Python files. In this case, `config_user.yaml` might then include `Dropbox: "/Users/jacob/Dropbox (Personal)/VirusPolicy"` and `external.txt` would include `county_day_data.csv | "{Dropbox}/county_day_data_20200625.csv"`. Stata/R/Python programs would remain unchanged, and `external.txt` would be updated as we change file versions.

This is what I had in mind when I suggested file versioning should be moved to within the "main code" (ie I meant within committed code, not within Stata/R/Python). This is similar to what we've implemented in VirusGPS. I'd appreciate your guidance as to whether you think this is best practice or if you'd suggest an alternative implementation. Thanks!

**Comment by gentzkow** [comment]
Thanks @jcconway. 

Thoughts:

1. The /log/source_XXX.log output files are designed to provide  record of the file versions that were used in any given run. I think this is a robust way to *document* file versions used, in the sense of allowing us to confirm those versions ex post.

2. That said, I like your suggested implementation. My idea with config_user.yaml was that it would include a small number (<=5 typically) of directory locations that might differ across local machines. The comments in config_user_template.yaml should provide clear instructions that would allow a user who had made a fresh clone of the repository to fill in these paths easily. E.g., "Path to the top level VirusPolicy directory on GSLab Dropbox." These should typically be paths to shared storage like GSLab Dropbox so the user doesn't have to do some separate download of files, unless there's a clear reason for that. 

3. It looks to me like we need to find a way to update the instructions for config_user_template.yaml (within that file and/or in the template documentation) to make the intended use clear. What I'd like to see in the template is something like 

```
external:

  # Path to shared VirusPolicy data directory on GSLab Dropbox
  county_daily_data: "/Path to GSLab Dropbox/VirusPolicy/"

  # Path to county-data-place Safegraph data on GSLab Dropbox
  county_daily_data_plac: "/Path to GSLab Dropbox/VirusPolicy/county_daily_data_plac/"

  etc.
```
rather than

```
external:
  county_daily_data: "/Users/bgoldman/Dropbox/Research/VirusPolicy/county_weekly_safegraph_5_6_2020_w_nyc 2/county_daily_data.csv"
  county_daily_data_plac: "/Users/bgoldman/Dropbox/Research/VirusPolicy/county_weekly_safegraph_5_6_2020_w_nyc 2/county_daily_data_plac.csv"
  etc.
```
